[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Top Speed SMP"
authors = [{name = "Canon", email = "canon@rhit.cf"}, {name = "Joey"}, {name = "Josh"}]
dynamic = ["version", "description"]
